#!/usr/bin/env python3
"""Set up an empty content store in this repo (the folder above tools/).
Creates what is missing, never overwrites: folder layout, empty data files, skeleton para.py and
descriptions.py, README, .gitignore, Obsidian attachment setting. Safe to run again.
  init.py           create what is missing
  init.py --check   only list what is missing (exit code 1 if anything is)"""
import sys, json
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent

DIRS = ["00_Staging/daily-notes", "00_Staging/articles", "raw/attachments", "notes", "01_Projects", "02_Areas",
        "03_Resources", "04_Archive/daily-notes", "04_Archive/pdf", "attachments"]
PARA = '''# PARA layer: projects and areas are hand-written notes (created once by link.py, never overwritten).
# Hubs in notes/ stay flat; each hub gets a para/status property and optional up-links.
# Fill these with /tn-cstore-init or /tn-cstore-assign. Example:
#   AREAS = {"Investing": {"text": "Ongoing responsibility: ...", "hubs": ["Macro", "ETFs"]}}
#   PROJECTS = {"Blog launch": {"text": "Outcome: ...", "hubs": ["Writing"]}}
AREAS = {
}
PROJECTS = {
}
ARCHIVE = {}          # "Hub": "reason it is archived"
RESOURCE_GROUPS = {   # "Group title": ["topic", ...] for topics not in an area (index layout only)
}
'''
DESC = '''# One line per hub note. type: topic | person | entity | concept
# Terms listed here are the vocabulary: `ingest.py vocab` shows them even before any article uses them.
D = {
}

# Other spellings that count as a mention of a hub in a summary (regex patterns). Optional.
# Example: "Federal Reserve": [r"Federal Reserve", r"Fed"],
ALIASES = {
}
'''
README = '''# Content store

Saved articles and links, fetched to markdown, summarised, tagged and linked for Obsidian.
Grown with the `/tn-cstore-*` commands in Claude Code. Guide: `docs/tn-cstore-user-guide.md`.

**0 of 0 links fetched.**

## Start here

1. Create your own repo from this template (GitHub: "Use this template"), clone it.
2. Open Claude Code in the repo root and run `/tn-cstore-init`. It sets up the folders and asks for your first areas, projects and topics.
3. Open the repo root as an Obsidian vault.
4. Drop daily notes (`YYYY-MM-DD.md` with links) into `00_Staging/daily-notes/` or articles (`.md`, `.pdf`) into `00_Staging/articles/`, then run `/tn-cstore-ingest-daily` or `/tn-cstore-ingest-article`.

Needs Python 3 and `pip3 install --user -r tools/requirements.txt`.

## Structure

- `00_Staging/`: inbox. `daily-notes/` (files named `YYYY-MM-DD.md` with links), `articles/` (markdown or PDF).
- `raw/`: full text (`<slug>.md`, no links) and summaries (`<slug>.summary.md`, the only place with backlinks). `raw/attachments/` holds the images.
- `notes/`: generated hub notes (topics, people, entities, concepts) and `_index.md`.
- `01_Projects/`, `02_Areas/`: hand-written notes, created once and never overwritten.
- `03_Resources/`: for files you move in. `04_Archive/`: processed daily notes and PDFs.
- `tools/`: the scripts and the data (`classification.json`, `descriptions.py`, `para.py`, `urls.tsv`, `results.json`).

Open the repo root as an Obsidian vault. The table below is regenerated by `tools/link.py`.

## Not fetched
'''
FILES = {
    "tools/classification.json": "{}\n",
    "tools/results.json": "[]\n",
    "tools/urls.tsv": "",
    "tools/ingest-state.json": json.dumps({"articles": {}, "daily": {}}, indent=1) + "\n",
    "tools/para.py": PARA,
    "tools/descriptions.py": DESC,
    "README.md": README,
    ".obsidian/app.json": json.dumps({"alwaysUpdateLinks": True, "attachmentFolderPath": "attachments"}, indent=2) + "\n",
}
IGNORE = ["__pycache__/", ".obsidian/workspace.json"]

def missing():
    out = [d + "/" for d in DIRS if not (ROOT / d).is_dir()]
    out += [f for f in FILES if not (ROOT / f).exists()]
    gi = (ROOT / ".gitignore").read_text().splitlines() if (ROOT / ".gitignore").exists() else []
    out += [f".gitignore: {x}" for x in IGNORE if x not in gi]
    return out

def main():
    todo = missing()
    if "--check" in sys.argv:
        print("\n".join(todo) or "complete"); raise SystemExit(1 if todo else 0)
    for d in DIRS:
        p = ROOT / d
        if not p.is_dir():
            p.mkdir(parents=True); (p / ".gitkeep").touch(); print("created", d + "/")
    for f, text in FILES.items():
        p = ROOT / f
        if p.exists(): continue
        p.parent.mkdir(parents=True, exist_ok=True); p.write_text(text); print("created", f)
    gi = ROOT / ".gitignore"
    lines = gi.read_text().splitlines() if gi.exists() else []
    add = [x for x in IGNORE if x not in lines]
    if add:
        gi.write_text("\n".join(lines + add) + "\n"); print("updated .gitignore:", ", ".join(add))
    print("store ready" if todo else "nothing to do, store already set up")
    print("Next: areas and projects in tools/para.py, starting vocabulary in tools/descriptions.py (or /tn-cstore-init), then python3 tools/link.py and python3 tools/check.py")

if __name__ == "__main__":
    main()
